### PR TITLE
implment loose option

### PR DESCRIPTION
**Pull request by shellscape**
@jwilsson how's this look? should provide really loosey goosey parsing for css-like langs.

optional thought: should this be the default, and should this module not care about validating strict css rules?

### CODE REVIEW

**Comment by jwilsson** [comment]
I think `loose` should be off as default, the main goal should be to parse "regular" CSS as close to the browsers as possible.

**Comment by shellscape** [comment]
Aye. It looks lik PostCSS waits until the parsing phase to check and throw for errors. It also looks like I shouldn't be doing the in-depth logical checks in tokenizer (if I want to follow suit). Unclosed paren errors are the only thing that PostCSS throws in the tokenizer, which makes sense because that has to be caught earlier. So I've got a little refactoring to do yet.

**Comment by shellscape** [comment]
@jwilsson just pushed the refactor. loose mode tests added and should be good to go for lesshint and others that don't need strict parsing.

**Comment by shellscape** [comment]
@jonathantneal jacobp100 you folks might also have interest in this PR

**Comment by jwilsson** [comment]
Nice, I'll pull it down and run `lesshint`'s tests on it.

**Comment by jwilsson** [comment]
All of `lesshint`'s tests pass with `loose: true`. I'm good!

**Pull request merged**
